// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rirrzbojxtexjwonnlka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpcnJ6Ym9qeHRleGp3b25ubGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5ODMyNDQsImV4cCI6MjA1NDU1OTI0NH0.uFmZ15LgbymP3fHrqkV8VBi7HaSo8UeB2eAXsCYCS-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);